# A compose file that is the equivalent of running docker manually.
#   docker run -it --rm -p 4242:4242 --name burble-bin-rcvr burble-bin:0.1.0 Rcvr
#   docker run -it --rm --name burble-bin-fkop burble-bin:0.1.0 FakeOperator
#   docker run -it --rm -p 2424:2424 --name burble-bin-sndr burble-bin:0.1.0 Sndr
# The broker is started with the following:
#   docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:4.0-management


services:
  #  TODO
  #  rabbitMqBroker:
  #    image: ...

  rcvr:
    image: burble-bin:0.1.0
    ports:
      - "4242:4242"
    command: Rcvr
#    depends_on:
#      - rabbit broker

  fakeOperator:
    image: burble-bin:0.1.0
    command: FakeOperator
    depends_on:
      - rcvr
    #  - rabbitMqBroker

  sndr:
    image: burble-bin:0.1.0
    command: Sndr
    depends_on:
      - fakeOperator

