# Postgres props
user=brbl_pushr
password=brbl_pushr
ssl=false
preparedStatementCacheQueries=5

# Connection pool (c3p0) config
driverClass=org.postgresql.Driver
jdbcUrl=jdbc:postgresql://localhost:5432/brbl_db_dev?currentSchema=brbl_biz,brbl_logic_9,brbl_logs_2,brbl_users
initialPoolSize=3
minPoolSize=2
maxPoolSize=4
acquireIncrement=2


