# Configuration for the ChttrClient webserver
chttr.listener.port=2424

# Configuration for the HttpMoHandler
chttr.mo.protocol=http
chttr.mo.host=192.168.1.155
chttr.mo.port=4242
chttr.mo.pathInfo=/brblEnqueue

# Postgres props
user=brbl_admin
password=brbl_admin
ssl=false
preparedStatementCacheQueries=10

# Connection pool (c3p0) config
driverClass=org.postgresql.Driver
#jdbcUrl=jdbc:postgresql://localhost:5432/brbl_db_dev
jdbcUrl=jdbc:postgresql://host.docker.internal:5432/brbl_db_dev
initialPoolSize=3
minPoolSize=2
maxPoolSize=4
acquireIncrement=2