##
# IMPORTANT: Do not include search_path param to jdbcUrl.
##

# Postgres props
user=brbl_admin
password=brbl_admin
ssl=false

# Connection pool (c3p0) config
driverClass=org.postgresql.Driver
jdbcUrl=jdbc:postgresql://localhost:5432/brbl_db_dev?currentSchema=brbl_biz,brbl_history,brbl_logic_8,brbl_logs_2,brbl_users
initialPoolSize=1
minPoolSize=1
maxPoolSize=1
acquireIncrement=1
