# Helidon implements JEP-290 preventing any class not in this whitelist from being deserialized.
# MWS: Update the content as needed if we see deserialization filtering REJECTing classes.
pattern=java.**;com.enoughisasgoodasafeast.**
