import csv
import random

# Generated by Gemini.
qa_pairs = [
    ("What is the capital of France?", ["Paris", "The city of lights."]),
    ("Who wrote 'To Kill a Mockingbird'?", ["Harper Lee", "It was Harper Lee."]),
    ("What is the boiling point of water at sea level?", ["100°C", "212°F", "It depends on the atmospheric pressure."]),
    ("What is your favorite color?", ["Blue", "Green", "Red"]),
    ("What is the meaning of life?", ["42", "To be happy and to help others.", "There is no single answer to this profound question."]),
    ("What is the best programming language?", ["Python for its readability and versatility.", "JavaScript for web development.", "It really depends on the specific application and developer preference."]),
    ("Should pineapple belong on pizza?", ["Yes, the sweetness complements the savory flavors.", "Absolutely not, it's a culinary crime.", "It's a matter of personal taste."]),
    ("What is the tallest mountain in the world?", ["Mount Everest", "Its peak is 8,848.86 meters above sea level."]),
    ("Who is the current President of the United States?", ["As of my last update, it is Joe Biden."]),
    ("What is the largest ocean on Earth?", ["The Pacific Ocean", "It covers about one-third of the surface of the Earth."]),
    ("What is the square root of 64?", ["8", "It's the number that, when multiplied by itself, equals 64."]),
    ("What is the chemical symbol for gold?", ["Au", "It comes from the Latin word for gold, 'aurum'."]),
    ("What is the best way to learn a new skill?", ["Consistent practice is key.", "Finding a good mentor can accelerate learning.", "Taking structured online courses can be very effective."]),
    ("What is your opinion on artificial intelligence?", ["It has the potential to solve many of the world's most pressing problems.", "It poses significant ethical and societal risks that we need to address carefully.", "It is a powerful tool, and its impact will depend on how we choose to use it."]),
    ("What is the most important thing in a relationship?", ["Trust is the foundation.", "Open and honest communication is crucial.", "Shared values and mutual respect are essential."]),
    ("What is your favorite food?", ["Pizza is a classic for a reason.", "I love the complexity and freshness of sushi.", "A well-made taco is hard to beat."]),
    ("What is the best movie ever made?", ["Many critics say 'The Godfather' is a masterpiece.", "'The Shawshank Redemption' is a popular choice for its emotional depth.", "It's entirely subjective and depends on personal preference."]),
    ("What is the primary cause of climate change?", ["The scientific consensus is that it's primarily caused by human activities, especially the burning of fossil fuels.", "Natural climate cycles have always existed, but the current rate of change is unprecedented."]),
    ("What is the ideal duration for a vacation?", ["One week is enough to recharge without getting bored.", "Two weeks allows for deeper relaxation and exploration.", "It depends on the destination and the purpose of the trip."]),
    ("What is the key to a successful career?", ["Hard work and perseverance are non-negotiable.", "Building a strong professional network is vital.", "Continuous learning and adapting to new challenges is essential for long-term success."]),
    ("How many continents are there?", ["There are seven continents: Asia, Africa, North America, South America, Antarctica, Europe, and Australia."]),
    ("What is the currency of Japan?", ["The Japanese Yen (JPY)."]),
    ("Who painted the Mona Lisa?", ["Leonardo da Vinci", "It's one of the most famous works of art in the world."]),
    ("What is the hardest natural substance on Earth?", ["Diamond", "It is a 10 on the Mohs scale of hardness."]),
    ("What is the main ingredient in guacamole?", ["Avocado", "It's a delicious and healthy dip."]),
    ("What is your favorite animal?", ["Dogs are known for their loyalty and companionship.", "Cats are independent and mysterious creatures.", "Elephants are intelligent and majestic animals."]),
    ("What are the benefits of exercise?", ["It improves physical health and can help prevent chronic diseases.", "It's a great way to reduce stress and improve mental well-being.", "Regular exercise can boost energy levels and improve sleep quality."]),
    ("What is the best book you've ever read?", ["'1984' by George Orwell is a chilling and thought-provoking classic.", "'The Lord of the Rings' by J.R.R. Tolkien is an epic fantasy adventure.", "'Sapiens' by Yuval Noah Harari provides a fascinating look at human history."]),
    ("What is your dream job?", ["A doctor, so I can help people.", "An artist, so I can express my creativity.", "A software engineer, so I can build innovative things."]),
    ("What is the greatest invention of all time?", ["The printing press revolutionized communication and the spread of knowledge.", "The internet has connected the world in unprecedented ways.", "The discovery and harnessing of electricity transformed modern life."]),
    ("What is the most beautiful place you've ever visited?", ["The Grand Canyon is breathtaking in its scale and beauty.", "The Greek island of Santorini is famous for its stunning sunsets and white-washed villages.", "The ancient temples and gardens of Kyoto, Japan are serene and beautiful."]),
    ("What is your biggest fear?", ["Many people are afraid of spiders (arachnophobia).", "A fear of heights (acrophobia) is also very common.", "Public speaking can be a major source of anxiety for some."]),
    ("What makes a good friend?", ["Loyalty and trustworthiness are essential qualities.", "A good sense of humor can make any situation better.", "A true friend is someone who listens without judgment."]),
    ("What is your favorite season?", ["Spring, when everything is in bloom.", "Summer, for the long days and warm weather.", "Autumn, with its crisp air and beautiful colors."]),
    ("What is the best advice you've ever received?", ["'This too shall pass' is a reminder that difficult times are temporary.", "'Be yourself; everyone else is already taken' is a quote by Oscar Wilde.", "'The only way to do great work is to love what you do' is a quote by Steve Jobs."]),
    ("What is one thing you want to do before you die?", ["Travel the world and experience different cultures.", "Write a book and share my story.", "Learn to play a musical instrument."]),
    ("What is the biggest challenge facing the world today?", ["Climate change is an existential threat to our planet.", "Global poverty and inequality are major concerns.", "Political instability and conflict can have devastating consequences."]),
    ("What is your favorite holiday?", ["Christmas, for the festive spirit and time with family.", "Thanksgiving, for the food and gratitude.", "Halloween, for the costumes and spooky fun."]),
    ("What is a skill you would like to learn?", ["Playing the guitar is a popular choice.", "Becoming fluent in a new language opens up new worlds.", "Learning to code is a valuable skill in today's digital world."]),
    ("What is something you are grateful for?", ["My family and friends are the most important thing in my life.", "I am grateful for my health and well-being.", "I am grateful for the opportunity to learn and grow every day."]),
    ("What is the capital of Australia?", ["Canberra", "Many people mistakenly think it's Sydney."]),
    ("Who discovered penicillin?", ["Alexander Fleming in 1928."]),
    ("What is the largest planet in our solar system?", ["Jupiter", "It is a gas giant."]),
    ("What is the formula for calculating the area of a circle?", ["πr² (pi times the radius squared)."]),
    ("What is the most spoken language in the world by number of native speakers?", ["Mandarin Chinese", "English is the most spoken by total number of speakers."]),
    ("What is your favorite hobby?", ["Reading is a great way to relax and learn.", "Hiking allows me to connect with nature.", "Playing video games can be a fun and immersive experience."]),
    ("What is the best way to relax?", ["Listening to calming music.", "Taking a warm bath.", "Practicing mindfulness or meditation."]),
    ("What is a common misconception?", ["That lightning never strikes the same place twice.", "That we only use 10% of our brains."]),
    ("What is your favorite type of music?", ["Rock and roll has a timeless energy.", "Pop music is catchy and fun to dance to.", "Classical music can be very moving and emotional."]),
    ("What is a food you dislike?", ["Many people have a strong aversion to Brussels sprouts.", "The taste of black licorice can be polarizing.", "Olives are another food that people either love or hate."]),
    ("What's the best way to learn a new language?", ["Immersing yourself in the culture where the language is spoken.", "Using language learning apps and websites consistently.", "Finding a language exchange partner to practice with."]),
    ("What are some tips for staying focused while working from home?", ["Create a dedicated workspace.", "Stick to a regular routine and schedule.", "Minimize distractions by turning off notifications."]),
    ("What's your favorite thing about your city?", ["The vibrant and diverse food scene.", "The abundance of parks and green spaces.", "The unique architecture and history."]),
    ("What's a book that changed your perspective on something?", ["'Sapiens: A Brief History of Humankind' by Yuval Noah Harari.", "'Thinking, Fast and Slow' by Daniel Kahneman.", "'The Sixth Extinction: An Unnatural History' by Elizabeth Kolbert."]),
    ("What's a common misconception about your profession?", ["That all programmers are introverted and work in isolation.", "That teachers have short work days and long vacations.", "That graphic designers just 'make things pretty'."]),
    ("What's a simple recipe that anyone can make?", ["Spaghetti Aglio e Olio is a classic Italian dish with just a few ingredients.", "A grilled cheese sandwich is a comforting and easy meal.", "Scrambled eggs are a quick and nutritious breakfast."]),
    ("What are the benefits of meditation?", ["It can reduce stress and anxiety.", "It can improve focus and concentration.", "It can promote a sense of inner peace and well-being."]),
    ("What's a travel destination that's on your bucket list?", ["Seeing the Northern Lights in Iceland.", "Exploring the ancient ruins of Machu Picchu in Peru.", "Going on a safari in the Serengeti."]),
    ("What's a small change that can have a big impact on the environment?", ["Using a reusable water bottle and coffee cup.", "Reducing food waste by planning meals and composting.", "Choosing to walk, bike, or take public transit instead of driving."]),
    ("What's your favorite way to exercise?", ["Going for a run in the park.", "Taking a yoga class to stretch and de-stress.", "Lifting weights at the gym to build strength."]),
    ("What's a skill you think everyone should learn?", ["Basic first aid and CPR.", "How to cook a few simple, healthy meals.", "Financial literacy and how to manage a budget."]),
    ("What's a piece of advice you'd give to your younger self?", ["Don't be afraid to fail.", "Invest in your relationships.", "It's okay to not have everything figured out."]),
    ("What's a movie that always makes you laugh?", ["'Step Brothers' is hilariously absurd.", "'Bridesmaids' has some unforgettable comedic scenes.", "'Monty Python and the Holy Grail' is a classic for a reason."]),
    ("What's your favorite type of music to listen to while you work?", ["Instrumental music helps me focus.", "Upbeat electronic music keeps me energized.", "I prefer to work in silence."]),
    ("What's a creative way to use leftover food?", ["Make a 'kitchen sink' frittata with leftover vegetables and cheese.", "Turn stale bread into croutons or breadcrumbs.", "Use vegetable scraps to make a flavorful broth."]),
    ("What's a common productivity myth?", ["That you need to be busy all the time to be productive.", "That multitasking is an effective way to get more done.", "That you can function on just a few hours of sleep."]),
    ("What's a good way to start a conversation with someone new?", ["Ask them about their hobbies or interests.", "Comment on something you have in common, like the event you're both at.", "Give them a sincere compliment."]),
    ("What's your favorite thing to do on a rainy day?", ["Curl up with a good book and a cup of tea.", "Have a movie marathon.", "Bake something delicious."]),
    ("What's a simple pleasure that always brightens your day?", ["The first sip of coffee in the morning.", "Feeling the sun on your face.", "Hearing a favorite song on the radio."]),
    ("What's a historical event you find fascinating?", ["The rise and fall of the Roman Empire.", "The Renaissance and the explosion of art and science.", "The Space Race and the first moon landing."]),
    ("What's a podcast you'd recommend?", ["'Radiolab' for its fascinating stories about science and curiosity.", "'How I Built This' for inspiring interviews with entrepreneurs.", "'The Daily' for in-depth news and analysis."]),
    ("What's a common grammar mistake that people make?", ["Confusing 'your' and 'you're'.", "Mixing up 'there', 'their', and 'they're'.", "Using apostrophes incorrectly for plurals."]),
    ("What's a fun fact you recently learned?", ["A group of flamingos is called a flamboyance.", "Octopuses have three hearts.", "Honey never spoils."]),
    ("What's a good way to de-stress after a long day?", ["Take a walk in nature.", "Practice deep breathing exercises.", "Listen to calming music or a guided meditation."]),
    ("What's your favorite board game or card game?", ["'Catan' is a classic strategy game.", "'Cards Against Humanity' is always a hit at parties.", "'Ticket to Ride' is fun for the whole family."]),
    ("What's a piece of technology you can't live without?", ["My smartphone, for better or worse.", "My noise-cancelling headphones are a lifesaver.", "My coffee maker is essential for starting my day."]),
    ("What's a question you wish people would ask you more often?", ["'What are you passionate about?'", "'What's something you've learned recently?'", "'How can I help you with that?'"]),
    ("What's a challenge you're currently working on?", ["Learning a new language.", "Training for a marathon.", "Trying to be more patient and understanding."]),
    ("What's a goal you're hoping to achieve this year?", ["Read more books.", "Save up for a big trip.", "Spend more quality time with loved ones."]),
    ("What's a tradition you have with your friends or family?", ["A weekly game night.", "An annual camping trip.", "A special meal we always cook for birthdays."]),
    ("What's a food you could eat every day?", ["A fresh, crisp apple.", "A perfectly ripe avocado.", "A warm, crusty piece of bread."]),
    ("What's a documentary that taught you something new?", ["'My Octopus Teacher' was a beautiful and moving film.", "'The Social Dilemma' was a wake-up call about the impact of social media.", "'Planet Earth' is always a stunning and educational watch."]),
    ("What's a common mistake people make when trying to save money?", ["Not having a clear budget.", "Making impulsive purchases.", "Not automating their savings."]),
    ("What's a hobby you've always wanted to try?", ["Pottery and ceramics.", "Rock climbing.", "Ballroom dancing."]),
    ("What's your favorite season and why?", ["Autumn, for the cool weather and cozy sweaters.", "Summer, for the long days and outdoor activities.", "Winter, for the holidays and the quiet beauty of the snow."]),
    ("What's a quote that inspires you?", ["'The future belongs to those who believe in the beauty of their dreams.' - Eleanor Roosevelt", "'The only thing we have to fear is fear itself.' - Franklin D. Roosevelt", "'In the end, it's not the years in your life that count. It's the life in your years.' - Abraham Lincoln"]),
    ("What's a simple way to make someone's day?", ["Give them a genuine compliment.", "Offer a helping hand without being asked.", "Send them a thoughtful message to let them know you're thinking of them."]),
    ("What's a fashion trend you don't understand?", ["Tiny sunglasses.", "Crocs.", "Low-rise jeans."]),
    ("What's an app you find surprisingly useful?", ["A plant identification app.", "A stargazing app.", "A language learning app."]),
    ("What's a YouTube channel you enjoy watching?", ["A channel that teaches you a new skill, like cooking or DIY.", "A channel that does deep dives into interesting topics.", "A channel that makes you laugh."]),
    ("What's a concert or live performance you'll never forget?", ["Seeing my favorite band play live for the first time.", "A classical music performance in a beautiful concert hall.", "A stand-up comedy show that had me in tears."]),
    ("What's a common problem that has a simple solution?", ["Losing your keys - get a key finder.", "Forgetting passwords - use a password manager.", "Not drinking enough water - carry a reusable water bottle with you."]),
    ("What's a plant that's easy to take care of?", ["Snake plants are very low-maintenance.", "ZZ plants can tolerate low light and infrequent watering.", "Pothos are fast-growing and easy to propagate."]),
    ("What's a work of art that moved you?", ["'The Starry Night' by Vincent van Gogh.", "'Guernica' by Pablo Picasso.", "'The Thinker' by Auguste Rodin."]),
    ("What's your favorite type of cuisine?", ["Italian food is classic comfort food.", "Mexican food is full of bold flavors and fresh ingredients.", "Thai food has a wonderful balance of sweet, sour, salty, and spicy."]),
    ("What's a skill you've learned from a video game?", ["Problem-solving and critical thinking.", "Hand-eye coordination and reaction time.", "Teamwork and communication in multiplayer games."]),
    ("What's a place in your home that makes you feel relaxed?", ["My cozy reading nook.", "My sunny kitchen.", "My comfortable bed."]),
    ("What's a common myth about sleep?", ["That you can 'catch up' on sleep over the weekend.", "That drinking alcohol before bed helps you sleep better.", "That snoring is harmless."]),
    ("What's a good habit you'd like to develop?", ["Waking up earlier to have more time in the morning.", "Drinking more water throughout the day.", "Practicing gratitude every day."]),
    ("What's a song that's currently stuck in your head?", ["A catchy pop song from the radio.", "A song from a movie I just watched.", "A song I haven't heard in years that just popped into my head."])
]


with open('generated_conversations.tsv', 'w', newline='', encoding='utf-8') as tsvfile:
    writer = csv.writer(tsvfile, delimiter='\t')
    writer.writerow(['Question', 'Answer'])

    if len(qa_pairs) >= 100:
        selected_pairs = random.sample(qa_pairs, 100)
    else:
        selected_pairs = qa_pairs

    for question, answers in selected_pairs:
        num_answers_to_write = random.randint(1, min(len(answers), 3))
        selected_answers = random.sample(answers, num_answers_to_write)
        for answer in selected_answers:
            writer.writerow([question, answer])

print("Successfully generated conversations in generated_conversations.tsv")
