CREATE ROLE brbl_admin;
ALTER ROLE brbl_admin WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:NGmEauu6jQ3zNQ/SP7E0Rg==$ls1VQFnYNVoFy3vdzRjilX8WEReMNgPdAXzLAHaF4XU=:9GRtzaLbFygMQOFa2SycfHfFttJIe5fFXWCNypN7USc=';
CREATE ROLE brbl_biz_app;
ALTER ROLE brbl_biz_app WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:gtSPYG/g7mjGmH6blPHV8Q==$kGi4VMewR7udAzPiC/d6kj3hJ3NjI6xjBtWIxEclze8=:gA2YAHB0aG4WmV46z3ERnUVzoeeKhCy53E1SGsnbMdU=';
CREATE ROLE brbl_biz_app_role;
ALTER ROLE brbl_biz_app_role WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS;
CREATE ROLE brbl_biz_read_role;
ALTER ROLE brbl_biz_read_role WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS;
CREATE ROLE brbl_biz_write_role;
ALTER ROLE brbl_biz_write_role WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS;
CREATE ROLE brbl_history_write_role;
ALTER ROLE brbl_history_write_role WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS;
CREATE ROLE brbl_logic_read_role;
ALTER ROLE brbl_logic_read_role WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS;
CREATE ROLE brbl_logic_write_role;
ALTER ROLE brbl_logic_write_role WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS;
CREATE ROLE brbl_logs_read_role;
ALTER ROLE brbl_logs_read_role WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS;
CREATE ROLE brbl_logs_write_role;
ALTER ROLE brbl_logs_write_role WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS;
CREATE ROLE brbl_operator;
ALTER ROLE brbl_operator WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:EwxLJG4ctrZNTPH0KWxKkw==$EIqwTlXdA/s5s6BBR5HcVFhk75eLGycTCggHAjI78eM=:AdplXU39liu4Ot/FvpI1qjUOuq7Z77eNb4k8tPpXrLc=';
CREATE ROLE brbl_pushr;
ALTER ROLE brbl_pushr WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS;
CREATE ROLE brbl_rcvr;
ALTER ROLE brbl_rcvr WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:8riN7QD27bXFWPq3ReQj3A==$uvbC3Hb2ziFDZszxIacr1Y6/9JwS935UfV8p7EZ9+7Q=:vETf1Ob8sEad+9FSdeEV/wCGyzMEjcSMgCp2lqzkIjY=';
CREATE ROLE brbl_sndr;
ALTER ROLE brbl_sndr WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:NimBvS/R+zcv3qDoLIl3Hw==$xCVOqOLYBUZp6U9ZsN7pyhVoiMZy+uY8rM+pMNQecbU=:PRUX5QXQOiiLcRHl6hF7Y9z25PwmM6n9Ybc03BXVLIc=';
CREATE ROLE brbl_users_read_role;
ALTER ROLE brbl_users_read_role WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS;
CREATE ROLE brbl_users_rw_role;
ALTER ROLE brbl_users_rw_role WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS;
CREATE ROLE brbl_users_write_role;
ALTER ROLE brbl_users_write_role WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS;
CREATE ROLE mark;
ALTER ROLE mark WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS;
ALTER ROLE brbl_admin SET search_path TO 'brbl_logs', 'brbl_users', 'brbl_logic', 'brbl_biz';
ALTER ROLE mark SET search_path TO 'brbl_logs', 'brbl_users', 'brbl_logic', 'brbl_biz';
GRANT brbl_biz_app_role TO brbl_admin WITH ADMIN OPTION, INHERIT TRUE GRANTED BY mark;
GRANT brbl_biz_app_role TO brbl_biz_app WITH INHERIT TRUE GRANTED BY mark;
GRANT brbl_biz_read_role TO brbl_admin WITH ADMIN OPTION, INHERIT TRUE GRANTED BY mark;
GRANT brbl_biz_read_role TO brbl_biz_app_role WITH INHERIT TRUE GRANTED BY mark;
GRANT brbl_biz_write_role TO brbl_admin WITH ADMIN OPTION, INHERIT TRUE GRANTED BY mark;
GRANT brbl_biz_write_role TO brbl_biz_app_role WITH INHERIT TRUE GRANTED BY mark;
GRANT brbl_history_write_role TO brbl_operator WITH INHERIT TRUE GRANTED BY mark;
GRANT brbl_logic_read_role TO brbl_admin WITH ADMIN OPTION, INHERIT TRUE GRANTED BY mark;
GRANT brbl_logic_read_role TO brbl_operator WITH INHERIT TRUE GRANTED BY mark;
GRANT brbl_logic_read_role TO brbl_pushr WITH INHERIT TRUE GRANTED BY mark;
GRANT brbl_logic_write_role TO brbl_admin WITH ADMIN OPTION, INHERIT TRUE GRANTED BY mark;
GRANT brbl_logic_write_role TO brbl_operator WITH INHERIT TRUE GRANTED BY mark;
GRANT brbl_logic_write_role TO brbl_pushr WITH INHERIT TRUE GRANTED BY mark;
GRANT brbl_logs_read_role TO brbl_admin WITH ADMIN OPTION, INHERIT TRUE GRANTED BY mark;
GRANT brbl_logs_write_role TO brbl_admin WITH ADMIN OPTION, INHERIT TRUE GRANTED BY mark;
GRANT brbl_logs_write_role TO brbl_operator WITH INHERIT TRUE GRANTED BY mark;
GRANT brbl_logs_write_role TO brbl_pushr WITH INHERIT TRUE GRANTED BY brbl_admin;
GRANT brbl_logs_write_role TO brbl_rcvr WITH INHERIT TRUE GRANTED BY mark;
GRANT brbl_logs_write_role TO brbl_sndr WITH INHERIT TRUE GRANTED BY mark;
GRANT brbl_users_read_role TO brbl_admin WITH ADMIN OPTION, INHERIT TRUE GRANTED BY mark;
GRANT brbl_users_read_role TO brbl_pushr WITH INHERIT TRUE GRANTED BY brbl_admin;
GRANT brbl_users_rw_role TO brbl_admin WITH ADMIN OPTION, INHERIT TRUE GRANTED BY mark;
GRANT brbl_users_rw_role TO brbl_operator WITH INHERIT TRUE GRANTED BY brbl_admin;
GRANT brbl_users_rw_role TO brbl_operator WITH INHERIT TRUE GRANTED BY mark;
GRANT brbl_users_write_role TO brbl_admin WITH ADMIN OPTION, INHERIT TRUE GRANTED BY mark;
GRANT brbl_users_write_role TO brbl_operator WITH INHERIT TRUE GRANTED BY brbl_admin;
GRANT USAGE ON SCHEMA brbl_biz TO brbl_biz_read_role;
GRANT USAGE ON SCHEMA brbl_biz TO brbl_biz_write_role;
GRANT USAGE ON SCHEMA brbl_history TO brbl_history_write_role;
GRANT USAGE ON SCHEMA brbl_logic TO brbl_logic_read_role;
GRANT USAGE ON SCHEMA brbl_logic TO brbl_logic_write_role;
GRANT USAGE ON SCHEMA brbl_logs TO brbl_logs_write_role;
GRANT USAGE ON SCHEMA brbl_logs TO brbl_logs_read_role;
GRANT USAGE ON SCHEMA brbl_logs_2 TO brbl_logs_read_role;
GRANT USAGE ON SCHEMA brbl_logs_2 TO brbl_logs_write_role;
GRANT USAGE ON SCHEMA brbl_users TO brbl_users_rw_role;
GRANT USAGE ON SCHEMA brbl_users TO brbl_users_read_role;
GRANT USAGE ON SCHEMA brbl_users TO brbl_users_write_role;
GRANT SELECT ON TABLE brbl_biz.addresses TO brbl_biz_read_role;
GRANT INSERT,UPDATE ON TABLE brbl_biz.addresses TO brbl_biz_write_role;
GRANT SELECT ON TABLE brbl_biz.customer_addresses TO brbl_biz_read_role;
GRANT INSERT,UPDATE ON TABLE brbl_biz.customer_addresses TO brbl_biz_write_role;
GRANT SELECT ON TABLE brbl_biz.payment_cc TO brbl_biz_read_role;
GRANT INSERT,UPDATE ON TABLE brbl_biz.payment_cc TO brbl_biz_write_role;
GRANT INSERT,UPDATE ON TABLE brbl_history.user_history TO brbl_history_write_role;
GRANT INSERT,UPDATE ON TABLE brbl_logic.campaign_users TO brbl_logic_write_role;
GRANT SELECT ON TABLE brbl_logic.campaign_users TO brbl_logic_read_role;
GRANT SELECT ON TABLE brbl_logic.edges TO brbl_logic_read_role;
GRANT SELECT ON TABLE brbl_logic.keywords TO brbl_logic_read_role;
GRANT SELECT ON TABLE brbl_logic.nodes TO brbl_logic_read_role;
GRANT INSERT,UPDATE ON TABLE brbl_logic.push_campaigns TO brbl_logic_write_role;
GRANT SELECT ON TABLE brbl_logic.push_campaigns TO brbl_logic_read_role;
GRANT SELECT ON TABLE brbl_logic.routes TO brbl_logic_read_role;
GRANT SELECT ON TABLE brbl_logic.scripts TO brbl_logic_read_role;
GRANT INSERT,DELETE,UPDATE ON TABLE brbl_logic.sessions TO brbl_logic_write_role;
GRANT SELECT ON TABLE brbl_logic.sessions TO brbl_logic_read_role;
GRANT INSERT ON TABLE brbl_logs.messages_mo TO brbl_logs_write_role;
GRANT SELECT ON TABLE brbl_logs.messages_mo TO brbl_logs_read_role;
GRANT INSERT ON TABLE brbl_logs.messages_mo_prcd TO brbl_logs_write_role;
GRANT SELECT ON TABLE brbl_logs.messages_mo_prcd TO brbl_logs_read_role;
GRANT INSERT ON TABLE brbl_logs.messages_mt TO brbl_logs_write_role;
GRANT SELECT ON TABLE brbl_logs.messages_mt TO brbl_logs_read_role;
GRANT INSERT ON TABLE brbl_logs.messages_mt_dlvr TO brbl_logs_write_role;
GRANT SELECT ON TABLE brbl_logs.messages_mt_dlvr TO brbl_logs_read_role;
GRANT SELECT ON TABLE brbl_logs_2.messages_mo TO brbl_logs_read_role;
GRANT INSERT ON TABLE brbl_logs_2.messages_mo TO brbl_logs_write_role;
GRANT SELECT ON TABLE brbl_logs_2.messages_mo_prcd TO brbl_logs_read_role;
GRANT INSERT ON TABLE brbl_logs_2.messages_mo_prcd TO brbl_logs_write_role;
GRANT SELECT ON TABLE brbl_logs_2.messages_mt TO brbl_logs_read_role;
GRANT INSERT ON TABLE brbl_logs_2.messages_mt TO brbl_logs_write_role;
GRANT SELECT ON TABLE brbl_logs_2.messages_mt_dlvr TO brbl_logs_read_role;
GRANT INSERT ON TABLE brbl_logs_2.messages_mt_dlvr TO brbl_logs_write_role;
GRANT SELECT,INSERT,UPDATE ON TABLE brbl_users.amalgams TO brbl_users_rw_role;
GRANT SELECT ON TABLE brbl_users.amalgams TO brbl_users_read_role;
GRANT INSERT ON TABLE brbl_users.amalgams TO brbl_users_write_role;
GRANT SELECT,INSERT ON TABLE brbl_users.companies TO brbl_users_rw_role;
GRANT SELECT ON TABLE brbl_users.companies TO brbl_users_read_role;
GRANT INSERT ON TABLE brbl_users.companies TO brbl_users_write_role;
GRANT SELECT,INSERT ON TABLE brbl_users.customers TO brbl_users_rw_role;
GRANT SELECT ON TABLE brbl_users.customers TO brbl_users_read_role;
GRANT INSERT ON TABLE brbl_users.customers TO brbl_users_write_role;
GRANT SELECT,INSERT ON TABLE brbl_users.profiles TO brbl_users_rw_role;
GRANT SELECT ON TABLE brbl_users.profiles TO brbl_users_read_role;
GRANT INSERT ON TABLE brbl_users.profiles TO brbl_users_write_role;
GRANT SELECT,INSERT ON TABLE brbl_users.users TO brbl_users_rw_role;
GRANT SELECT ON TABLE brbl_users.users TO brbl_users_read_role;
GRANT INSERT,UPDATE ON TABLE brbl_users.users TO brbl_users_write_role;

-- 2026/09/19 Allow brbl_sndr to use getActiveRoutes query. Include Current pgroll schema views.
GRANT USAGE ON SCHEMA brbl_logic TO brbl_sndr;
GRANT USAGE ON SCHEMA brbl_logic_12 TO brbl_sndr;
GRANT SELECT ON TABLE brbl_logic.routes TO brbl_sndr;
GRANT SELECT ON TABLE brbl_logic_12.routes TO brbl_sndr;
GRANT SELECT ON TABLE brbl_logic.scripts TO brbl_sndr;
GRANT SELECT ON TABLE brbl_logic_12.scripts TO brbl_sndr;